### ISSUE TITLE
Auto clean just doesn't work

### ISSUE THREAD

**Issue by SirenGlitch** [tserumula/DbCleanerforWhatsapp#6] opened 2022-09-19 11:40 UTC
Android 11, got auto clean set to everyday at 3:00AM. It doesn't do anything, I check run history, nothing. I delete it my self, 150+MB of storage of backups not deleted by the auto deleter.

**Comment by tserumula** [comment] 2022-09-19 12:59
Hi SirenGlitch. If the run-history is not showing anything then it means the service is being killed in the background by the OS. Please **disable battery saver** or **white-list the app** so that it can auto-start at the scheduled time

**Comment by tserumula** [comment] 2022-09-25 11:22
Are you still experiencing the issue?

**Comment by SirenGlitch** [comment] 2022-09-25 11:31
> Are you still experiencing the issue?

It seemed to help, but it is still a bit hit or miss. Sometimes it works, other times it doesn't. It is a bit annoying that it doesn't always work but I have a reminder on my phone so that every weekend, I check if it worked, and clear anything left over. So in the end it ends up getting deleted anyway.

**Comment by LambdaSoft** [comment] 2022-09-26 08:25
I have this problem too, I think the problem is that if you restart the phone, you have to open the app first for it to start working

**Comment by tserumula** [comment] 2022-10-18 21:04
Hi guys. Please try this [beta version](https://github.com/tserumula/DbCleanerforWhatsapp/releases/tag/v1.3.3-beta) and check if the problem is fixed. The app will now start on boot so that the service is always running even when you restart the phone.

**Comment by SirenGlitch** [comment] 2022-10-19 16:07
> Hi guys. Please try this [beta version](https://github.com/tserumula/DbCleanerforWhatsapp/releases/tag/v1.3.3-beta) and check if the problem is fixed. The app will now start on boot so that the service is always running even when you restart the phone.

This seems to have worked, we'll have to wait to see if it works on other phones but it did on mine. Thanks!

**Comment by LambdaSoft** [comment] 2022-10-26 00:02
Another thing, WhatsApp Business backups aren't being cleaned (but normal WhatsApp backups yes), I don't know if I'm the only one with this problem

**Comment by SirenGlitch** [comment] 2022-10-26 00:09
> Another thing, WhatsApp Business backups aren't being cleaned (but normal WhatsApp backups yes), I don't know if I'm the only one with this problem

Are you using the beta of DBCleaner? It may be fixed in there

**Comment by LambdaSoft** [comment] 2022-10-26 04:52
> > Another thing, WhatsApp Business backups aren't being cleaned (but normal WhatsApp backups yes), I don't know if I'm the only one with this problem
> 
> Are you using the beta of DBCleaner? It may be fixed in there

Yes, I am using the last beta

**Comment by tserumula** [comment] 2022-11-07 07:10
> Another thing, WhatsApp Business backups aren't being cleaned (but normal WhatsApp backups yes), I don't know if I'm the only one with this problem

Hi. This one is not a bug, the auto-clean did not clear Whatsapp Business backups automatically (by design). I have changed this in new app update. You can now select which backups the app should clear when scheduled.

**Comment by tserumula** [comment] 2022-11-07 07:13
New app update here : [app v2.0](https://github.com/tserumula/DbCleanerforWhatsapp/releases/tag/v2.0.0)

If there are still some issues that are not resolved please do let me know. Otherwise I'll close this thread soon in a few days.

Thanks for all the feedback guys

**Closed** 2022-11-12 13:49 UTC
Labels: bug
